*-lnd-stop - now first time we use `lncli stop` command and if it will not help after 5 seconds - we try `kill`

diff --git a/configs/bin/lnd/mainnet-lnd-stop b/configs/bin/lnd/mainnet-lnd-stop
--- a/configs/bin/lnd/mainnet-lnd-stop
+++ b/configs/bin/lnd/mainnet-lnd-stop
@@ -6,6 +6,8 @@ bitcoin_network=mainnet
 tcp_port=9735
 service_name=lnd
 pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
+macaroon_path=$HOME/.lnd/admin-${bitcoin_network}.macaroon
+grpc_port=10009
 
 if [ ! -f $pid_file ]; then
     echo "ERROR: The ${service_name} (${bitcoin_network}) not run!"
@@ -20,12 +22,28 @@ if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
 fi
 
 echo -n "The ${service_name} (${bitcoin_network}) terminating ..."
-kill `cat $pid_file` &>/dev/null
+
+# First way - to try stop through `lncli stop` command but sometime it hangs up a long time
+lncli --macaroonpath ${macaroon_path} --rpcserver localhost:${grpc_port} stop &
+lncli_pid=$!
+
 for i in {1..5}; do
     kill -0 `cat $pid_file` &>/dev/null || break
     echo -n '.'
     sleep 1
 done
-kill -0 `cat $pid_file` &>/dev/null && echo "I cannot terminate ${service_name} (${bitcoin_network})" && exit 2
+
+if kill -0 `cat $pid_file` &>/dev/null; then
+    # If we here - the lnd works...
+    kill $lncli_pid &>/dev/null
+    kill `cat $pid_file` &>/dev/null
+    for i in {1..5}; do
+	kill -0 `cat $pid_file` &>/dev/null || break
+	echo -n '.'
+	sleep 1
+    done
+    kill -0 `cat $pid_file` &>/dev/null && echo "I cannot terminate ${service_name} (${bitcoin_network})" && exit 2
+fi
+
 echo " OK"
 rm -f $pid_file
