...

diff --git a/configs/bin/bitcoind/mainnet-bitcoind-start b/configs/bin/bitcoind/mainnet-bitcoind-start
--- a/configs/bin/bitcoind/mainnet-bitcoind-start
+++ b/configs/bin/bitcoind/mainnet-bitcoind-start
@@ -2,6 +2,8 @@
 
 . $HOME/.bitcoin_envs
 
-# TODO upnpc ports settuping
-bitcoind -conf $HOME/.bitcoin/bitcoin-mainnet.conf -pid $HOME/.mainnet-bitcoind.pid && echo "OK - bitcoind (mainnet) started"
+if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e 'The bitcoind (mainnet)' -a $$BITCOIN_KIT_LOCAL_IP$$ 8333 8333 tcp || echo "ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ 8333 8333 tcp)"
+fi
 
+bitcoind -conf $HOME/.bitcoin/bitcoin-mainnet.conf -pid $HOME/.mainnet-bitcoind.pid && echo "OK - bitcoind (mainnet) started"
diff --git a/configs/bin/bitcoind/mainnet-bitcoind-stop b/configs/bin/bitcoind/mainnet-bitcoind-stop
--- a/configs/bin/bitcoind/mainnet-bitcoind-stop
+++ b/configs/bin/bitcoind/mainnet-bitcoind-stop
@@ -2,6 +2,8 @@
 
 . $HOME/.bitcoin_envs
 
-# TODO upnpc ports settuping
-bitcoin-cli -conf $HOME/.bitcoin/bitcoin-mainnet.conf stop
+if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d 8333 tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d 8333 tcp)"
+fi
 
+bitcoin-cli -conf $HOME/.bitcoin/bitcoin-mainnet.conf stop
diff --git a/configs/bin/bitcoind/testnet-bitcoind-start b/configs/bin/bitcoind/testnet-bitcoind-start
--- a/configs/bin/bitcoind/testnet-bitcoind-start
+++ b/configs/bin/bitcoind/testnet-bitcoind-start
@@ -2,6 +2,8 @@
 
 . $HOME/.bitcoin_envs
 
-# TODO upnpc ports settuping
-bitcoind -conf $HOME/.bitcoin/bitcoin-testnet.conf -pid $HOME/.testnet-bitcoind.pid && echo "OK - bitcoind (testnet) started"
+if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e 'The bitcoind (testnet)' -a $$BITCOIN_KIT_LOCAL_IP$$ 18333 18333 tcp || echo "ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ 18333 18333 tcp)"
+fi
 
+bitcoind -conf $HOME/.bitcoin/bitcoin-testnet.conf -pid $HOME/.testnet-bitcoind.pid && echo "OK - bitcoind (testnet) started"
diff --git a/configs/bin/bitcoind/testnet-bitcoind-stop b/configs/bin/bitcoind/testnet-bitcoind-stop
--- a/configs/bin/bitcoind/testnet-bitcoind-stop
+++ b/configs/bin/bitcoind/testnet-bitcoind-stop
@@ -2,6 +2,9 @@
 
 . $HOME/.bitcoin_envs
 
-# TODO upnpc ports settuping
+if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d 18333 tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d 18333 tcp)"
+fi
+
 bitcoin-cli -conf $HOME/.bitcoin/bitcoin-testnet.conf stop
 
