RC1

diff --git a/configs/bin/bitcoind/mainnet-bitcoind-start b/configs/bin/bitcoind/mainnet-bitcoind-start
--- a/configs/bin/bitcoind/mainnet-bitcoind-start
+++ b/configs/bin/bitcoind/mainnet-bitcoind-start
@@ -2,7 +2,14 @@
 
 . $HOME/.bitcoin_envs
 
-bitcoind -conf=$HOME/.bitcoin/bitcoin-mainnet.conf && echo "OK - bitcoind (mainnet) started" &&
+service_name=bitcoind
+bitcoin_network=mainnet
+tcp_port=8333
+
+bitcoind -conf=$HOME/.bitcoin/bitcoin-${bitcoin_network}.conf && echo "OK - ${service_name} (${bitcoin_network}) started" &&
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e 'The bitcoind (mainnet)' -a $$BITCOIN_KIT_LOCAL_IP$$ 8333 8333 tcp || echo "ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ 8333 8333 tcp)"
+    echo -n "UPnP On (${service_name}/${bitcoin_network}) ..."
+    {
+	upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e "The ${service_name} (${bitcoin_network})" -a $$BITCOIN_KIT_LOCAL_IP$$ ${tcp_port} ${tcp_port} tcp
+    } &> /dev/null && echo " OK" || echo " ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ ${tcp_port} ${tcp_port} tcp)"
 fi
diff --git a/configs/bin/bitcoind/testnet-bitcoind-stop b/configs/bin/bitcoind/testnet-bitcoind-stop
--- a/configs/bin/bitcoind/testnet-bitcoind-stop
+++ b/configs/bin/bitcoind/testnet-bitcoind-stop
@@ -8,7 +8,10 @@ pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
 tcp_port=18333
 
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
+    echo -n "UPnP Off (${service_name}/${bitcoin_network}) ..."
+    {
+	upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp
+    } &> /dev/null && echo " OK" || echo " ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
 fi
 
 pid=`cat $pid_file`
diff --git a/configs/bin/lncli-web/testnet-lncli-web-start b/configs/bin/lncli-web/testnet-lncli-web-start
--- a/configs/bin/lncli-web/testnet-lncli-web-start
+++ b/configs/bin/lncli-web/testnet-lncli-web-start
@@ -2,15 +2,24 @@
 
 . $HOME/.bitcoin_envs
 
-pid_file=$HOME/.testnet-lncli-web.pid
+service_name=lncli-web
+bitcoin_network=testnet
+tcp_port=8281
+grpc_port=10010
+web_admin_pass=$$LNCLI_WEB_TESTNET_ADMIN_PASS$$
+web_limit_pass=$$LNCLI_WEB_TESTNET_LIMIT_PASS$$
+pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
 
 cd $HOME/opt/lncli-web &&
 if [ ! -f $pid_file ] || ! kill -0 `cat $pid_file` &>/dev/null; then
-    nohup node server --lndhost localhost:10010 --serverport 8281 --usetls ssl --user admin --pwd $$LNCLI_WEB_TESTNET_ADMIN_PASS$$ --limituser limit --limitpwd $$LNCLI_WEB_TESTNET_LIMIT_PASS$$ --serverhost $$BITCOIN_KIT_LOCAL_IP$$ &>/dev/null &
+    nohup node server --lndhost localhost:${grpc_port} --serverport ${tcp_port} --usetls ssl --user admin --pwd ${web_admin_pass} --limituser limit --limitpwd ${web_limit_pass} --serverhost $$BITCOIN_KIT_LOCAL_IP$$ &>/dev/null &
     echo $! >$pid_file
 else
-    echo 'testnet-lncli-web is already run (pid: '`cat $pid_file`')'
+    echo "${service_name} (${bitcoin_network}) is already run (pid: '`cat $pid_file`')"
 fi &&
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e 'The lncli-web (testnet)' -a $$BITCOIN_KIT_LOCAL_IP$$ 8281 8281 tcp || echo "ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ 8281 8281 tcp)"
+    echo -n "UPnP On (${service_name}/${bitcoin_network}) ..."
+    {
+	upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e "The ${service_name} (${bitcoin_network})" -a $$BITCOIN_KIT_LOCAL_IP$$ ${tcp_port} ${tcp_port} tcp
+    } &> /dev/null && echo " OK" || echo " ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ ${tcp_port} ${tcp_port} tcp)"
 fi
diff --git a/configs/bin/lnd/mainnet-lnd-stop b/configs/bin/lnd/mainnet-lnd-stop
--- a/configs/bin/lnd/mainnet-lnd-stop
+++ b/configs/bin/lnd/mainnet-lnd-stop
@@ -13,7 +13,10 @@ if [ ! -f $pid_file ]; then
 fi
 
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
+    echo -n "UPnP Off (${service_name}/${bitcoin_network}) ..."
+    {
+	upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp
+    } &> /dev/null && echo " OK" || echo " ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
 fi
 
 echo -n "The ${service_name} (${bitcoin_network}) terminating ..."
diff --git a/configs/bin/lnd/testnet-lnd-start b/configs/bin/lnd/testnet-lnd-start
--- a/configs/bin/lnd/testnet-lnd-start
+++ b/configs/bin/lnd/testnet-lnd-start
@@ -2,11 +2,25 @@
 
 . $HOME/.bitcoin_envs
 
+service_name=lnd
+bitcoin_network=testnet
+tcp_port=9736
+grpc_port=10010
+pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
+
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e 'The lnd (testnet)' -a $$BITCOIN_KIT_LOCAL_IP$$ 9736 9736 tcp || echo "ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ 9736 9736 tcp)"
+    echo -n "UPnP On (${service_name}/${bitcoin_network}) ..."
+    {
+	upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e "The ${service_name} (${bitcoin_network})" -a $$BITCOIN_KIT_LOCAL_IP$$ ${tcp_port} ${tcp_port} tcp
+    } &> /dev/null && echo " OK" || echo " ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ ${tcp_port} ${tcp_port} tcp)"
 fi
 
-{ nohup lnd --configfile=$HOME/.lnd/lnd-testnet.conf &>>$HOME/.lnd/testnet-lnd-run.log & echo $! > $HOME/.testnet-lnd.pid; } &>/dev/null
+{
+    nohup lnd --configfile=$HOME/.lnd/${service_name}-${bitcoin_network}.conf &>>$HOME/.lnd/${bitcoin_network}-${service_name}-run.log &
+    echo $! > $HOME/.${bitcoin_network}-${service_name}.pid
+} &>/dev/null
+
 sleep 1;
-echo 'Please unlock lnd daemon (testnet), enter password:';
-lncli --rpcserver localhost:10010 unlock
+
+echo $'\n\n\n******************************************************************\n\nPlease unlock '"${service_name} (${bitcoin_network})"$' daemon\n\n******************************************************************\nEnter password: ';
+lncli --rpcserver localhost:${grpc_port} unlock
