99% works :)

diff --git a/configs/bin/bitcoind/testnet-bitcoind-stop b/configs/bin/bitcoind/testnet-bitcoind-stop
--- a/configs/bin/bitcoind/testnet-bitcoind-stop
+++ b/configs/bin/bitcoind/testnet-bitcoind-stop
@@ -2,9 +2,24 @@
 
 . $HOME/.bitcoin_envs
 
+service_name=bitcoind
+bitcoin_network=testnet
+pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
+tcp_port=18333
+
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d 18333 tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d 18333 tcp)"
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
 fi
 
-bitcoin-cli -conf $HOME/.bitcoin/bitcoin-testnet.conf stop
+pid=`cat $pid_file`
 
+bitcoin-cli -conf=$HOME/.bitcoin/bitcoin-${bitcoin_network}.conf stop
+
+echo -n "The ${service_name} (${bitcoin_network}) terminating ..."
+for i in {1..20}; do
+    kill -0 $pid &>/dev/null || break
+    echo -n '.'
+    sleep 1
+done
+kill -0 $pid &>/dev/null && echo "I cannot terminate ${service_name} (${bitcoin_network})" && exit 2
+echo " OK"
diff --git a/configs/bin/lncli-web/mainnet-lncli-web-stop b/configs/bin/lncli-web/mainnet-lncli-web-stop
--- a/configs/bin/lncli-web/mainnet-lncli-web-stop
+++ b/configs/bin/lncli-web/mainnet-lncli-web-stop
@@ -2,24 +2,27 @@
 
 . $HOME/.bitcoin_envs
 
-service_name=bitcoind
 bitcoin_network=mainnet
+tcp_port=8280
+service_name=lncli-web
 pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
-tcp_port=8333
+
+if [ ! -f $pid_file ]; then
+    echo "ERROR: The ${service_name} (${bitcoin_network}) not run!"
+    exit 1
+fi
 
 if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
     upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
 fi
 
-pid=`cat $pid_file`
-
-bitcoin-cli -conf=$HOME/.bitcoin/bitcoin-${bitcoin_network}.conf stop
-
 echo -n "The ${service_name} (${bitcoin_network}) terminating ..."
-for i in {1..20}; do
-    kill -0 $pid &>/dev/null || break
+kill `cat $pid_file` &>/dev/null
+for i in {1..5}; do
+    kill -0 `cat $pid_file` &>/dev/null || break
     echo -n '.'
     sleep 1
 done
-kill -0 $pid &>/dev/null && echo "I cannot terminate ${service_name} (${bitcoin_network})" && exit 2
+kill -0 `cat $pid_file` &>/dev/null && echo "I cannot terminate ${service_name} (${bitcoin_network})" && exit 2
 echo " OK"
+rm -f $pid_file
diff --git a/configs/bin/lncli-web/testnet-lncli-web-start b/configs/bin/lncli-web/testnet-lncli-web-start
--- a/configs/bin/lncli-web/testnet-lncli-web-start
+++ b/configs/bin/lncli-web/testnet-lncli-web-start
@@ -10,4 +10,7 @@ if [ ! -f $pid_file ] || ! kill -0 `cat $pid_file` &>/dev/null; then
     echo $! >$pid_file
 else
     echo 'testnet-lncli-web is already run (pid: '`cat $pid_file`')'
+fi &&
+if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -e 'The lncli-web (testnet)' -a $$BITCOIN_KIT_LOCAL_IP$$ 8281 8281 tcp || echo "ERROR: i cannot add port redirection [$?] (upnpc -a $$BITCOIN_KIT_LOCAL_IP$$ 8281 8281 tcp)"
 fi
diff --git a/configs/bin/lnd/mainnet-lnd-stop b/configs/bin/lnd/mainnet-lnd-stop
--- a/configs/bin/lnd/mainnet-lnd-stop
+++ b/configs/bin/lnd/mainnet-lnd-stop
@@ -2,8 +2,27 @@
 
 . $HOME/.bitcoin_envs
 
-if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
-    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d 9735 tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d 9735 tcp)"
+bitcoin_network=mainnet
+tcp_port=9735
+service_name=lnd
+pid_file=$HOME/.${bitcoin_network}-${service_name}.pid
+
+if [ ! -f $pid_file ]; then
+    echo "ERROR: The ${service_name} (${bitcoin_network}) not run!"
+    exit 1
 fi
 
-kill `cat $HOME/.mainnet-lnd.pid` && rm -f $HOME/.mainnet-lnd.pid
+if [ "$$BITCOIN_KIT_UPNP_SUPPORT$$" == "Yes" ]; then
+    upnpc -m $$BITCOIN_KIT_LOCAL_IP$$ -d ${tcp_port} tcp || echo "ERROR: i cannot delete port redirection [$?] (upnpc -d ${tcp_port} tcp)"
+fi
+
+echo -n "The ${service_name} (${bitcoin_network}) terminating ..."
+kill `cat $pid_file` &>/dev/null
+for i in {1..5}; do
+    kill -0 `cat $pid_file` &>/dev/null || break
+    echo -n '.'
+    sleep 1
+done
+kill -0 `cat $pid_file` &>/dev/null && echo "I cannot terminate ${service_name} (${bitcoin_network})" && exit 2
+echo " OK"
+rm -f $pid_file
